### ISSUE TITLE
latest message contents display for all messages

### ISSUE THREAD

**Issue by otherwisehappycamper** [vanowm/TB-Auto-Select-Latest-Message#1]
I run Windows 10 Pro, updated, on a ThinkPad X1 Gen 2.  after upgrading to TB 78.6.0 (64-bit) i found the contents of the latest message were always displayed even when double-clicking on the older messages.  But after disabling Auto Select Latest Message [v.3.1.3], TB displays all message contents properly after double-clicking them.  This version of ASLM is shown as having  been updated on Dec. 18, 2020.  I use BitDefender Total Security, updated Dec.18/2020.

**Comment by vanowm** [comment]
Are there any other addons installed? if so, try disable them and see if the issue still present.
Also, by default double click on a message opens it in a new tab

I'm unable reproduce on my system with no other addons installed.

**Comment by otherwisehappycamper** [comment]
I have uninstalled both my other addons - (Compact Header and Manually Sort Folders) and restarted, but problem continues.  I will attempt to make some short videos showing issue and attach them here - oops, I couldn't make one small enough, so I've taken the following 5 pictures showing the sequence of  events; 1) only your ASLM addon installed and activated, 2) last message selected, contents correctly displayed in preview pane, 3) and this email's contents correctly displayed in full screen when double-clicked, 4) any other/older email selected (i chose yours), contents correctly displayed in preview pane, BUT 5) when double clicked, this (and all other/older emails') contents not displayed in full-screen.  Instead, the latest message received's contents are displayed in full screen.  I hope this helps.
 
![20201220_162144](https://user-images.githubusercontent.com/76236381/102724812-54ef2b80-42e0-11eb-8579-d3e26d830439.jpg)
![20201220_162200](https://user-images.githubusercontent.com/76236381/102724813-56b8ef00-42e0-11eb-97f1-26a64dcfbabf.jpg)
![20201220_162210](https://user-images.githubusercontent.com/76236381/102724815-5882b280-42e0-11eb-8932-7c7863ee16ae.jpg)
![20201220_162227](https://user-images.githubusercontent.com/76236381/102724816-59b3df80-42e0-11eb-977c-eec5fa343e79.jpg)
![20201220_162236](https://user-images.githubusercontent.com/76236381/102724817-5b7da300-42e0-11eb-9905-ad6e010fb6ee.jpg)

**Comment by vanowm** [comment]
Yes, I was able reproduce it. It's when new "Force" option is enabled (Options -> General tab).
As a work around you can try disable it.

**Comment by otherwisehappycamper** [comment]
That's all it was!  ASLM now working perfectly.  I'm sorry i didn't think of this myself - sorry to bother you.

**Comment by vanowm** [comment]
Well, it's a bug, it's not supposed to do that. Thanks for the report ;)

**Comment by otherwisehappycamper** [comment]
Delighted to be able to help.  Cheers.

**Comment by vanowm** [comment]
Fixed in v3.1.4
