### ISSUE TITLE
Request: separate settings for auto selection on folder change and/or startup

### ISSUE THREAD

**Issue by sofquipeut** [vanowm/TB-Auto-Select-Latest-Message#5]
Hello,

Could you please consider giving the possibility to choose either we want the autoselection occur on startup or folder change? I'm visually impaired using a screen reader and when navigating my folders tree to choose the right one, the cursor jumps suddenly from the tree to the message list potentially in the wrong folder and I have to go back to the tree with the tab key. However, I love the auto-selection feature which brings me directlyto the message list at startup. So it could be handy to have to separate settings for each.

Thanks

Sof

**Comment by vanowm** [comment]
Disable option "Auto focus on messages list"

**Comment by sofquipeut** [comment]
I've installed 3.2.0 but don't find this option...

**Comment by vanowm** [comment]
The option should be at TB Settings -> General -> Thunderbird Start Page

**Comment by sofquipeut** [comment]
I've found the option in TB settings and checked it. The cursor no longer jumps in the message list on folder change but the cursor of my screen reader is no longer placed in the message list at startup, making the module useless for me...

**Comment by vanowm** [comment]
Oh, now I understand the dilemma.

**Comment by sofquipeut** [comment]
Thanks! Works as expected now.
